language: node_js
node_js:
  - "8"
  - "6"
install:
  - npm install -g codecov
  - npm install -g istanbul
script:
  - make test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
