#!/usr/bin/env node
var fs = require('fs');
var JSONFix = require('./jsonfix');

if(process.argv.length === 2) {
  console.error('error: missing input file');
} else if(process.argv.length === 3) {
  var filepath = process.argv[2];
  var data = fs.readFile(filepath, {encoding: 'utf8'}, function(err, data) {
    if(err !== null) {
      console.error('cannot read file "'+process.argv[2]+'"');
      process.exit(1);
    } else {
      var result = JSONFix.process(data);

      // debug stuff
      // console.log('============');
      // console.log('isValid    = '+JSONFix.isValid);
      // console.log('wasFixed   = '+JSONFix.wasFixed);
      // console.log('message    = '+JSONFix.message);
      // console.log('totalTries = '+JSONFix.stats.totalTries);
      // console.log(JSON.stringify(JSONFix, null, 2));
      // console.log('============');

      console.log(JSON.stringify(result, null, 2));
    }
  });
}
